server:
  port: 12000

spring:
  application:
    name: blkmkt-ware
  cloud:
    nacos:
      discovery:
        server-addr: 39.101.64.188:8848
  datasource:
    username: root
    password: root
    url: jdbc:mysql://39.101.64.188:3306/blkmkt_ware?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 39.101.64.188
    username: admin
    password: admin
    listener:
      simple:
        acknowledge-mode: manual
    virtual-host: /



mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
