spring:
  cloud:
    gateway:
      routes:
        - id: third_party_route
          uri: lb://blkmkt-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: good_route
          uri: lb://blkmkt-good
          predicates:
            - Path=/api/good/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: order_route
          uri: lb://blkmkt-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: user_route
          uri: lb://blkmkt-user
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
