server:
  port: 7000

spring:
  application:
    name: blkmkt-product
  cloud:
    nacos:
      discovery:
        server-addr: 39.101.64.188:8848
  datasource:
    username: root
    password: root
    url: jdbc:mysql://39.101.64.188:3306/blkmkt_good?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
