server:
    port: 8081

spring:
    application:
        name: blkmkt-forum
    cloud:
        nacos:
            discovery:
                server-addr: 39.101.64.188:8848
    datasource:
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/bbs?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&allowMultiQueries=true
        driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
    mapper-locations: classpath:/mapper/**/*.xml
    global-config:
        db-config:
            id-type: auto